version: 0.0
os: linux
files:
  - source: /themes
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
  AfterInstall:
    - location: scripts/afterInstall.sh
    
