<?php
/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function memberform_webform_submission_presave(\Drupal\webform\Entity\WebformSubmission $submission) {
// kint($submission);
  // var_dump($submission); exit;
}

// function memberform_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
//   kint($hook);
//   echo "from here";
//   kint($variables);
//   if (\Drupal::currentUser()
//     ->isAuthenticated() && in_array($hook, array(
//     'node',
//     'taxonomy_term',
//   ))) {
//     $suggestions[] = $hook . '__' . 'logged_in';
//   }
// }